#DIMENSIONES EN NUMPY

In [1]:
import numpy as np

#SCALAR

In [4]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

#VECTOR

In [5]:
vector  = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

#MATRIZ 2 DIMENSIONES

In [7]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim


[[1 2 3]
 [4 5 6]]


2

#TENSOR -N DIMENSIONES

In [9]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3