#GENERACION DE DATOS ALEATORIOS

In [ ]:
import numpy as np

#ARANGE

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#ZEROS

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#ONES

In [ ]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#EYE

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#LINSPACE

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

#random

In [ ]:
np.random.rand()

0.2817135579640341

In [ ]:
np.random.rand(4)

array([0.93858768, 0.26329544, 0.50040563, 0.00498943])

In [ ]:
np.random.rand(4,4)

array([[0.14041396, 0.27233105, 0.5532112 , 0.32672897],
       [0.68408732, 0.08557067, 0.16430232, 0.48199495],
       [0.63703456, 0.1570224 , 0.02520606, 0.83655891],
       [0.6435335 , 0.84745859, 0.38618001, 0.37995669]])

In [ ]:
np.random.randint(1,100,(10,10))

array([[54, 46, 58, 99, 29, 49, 62, 30, 79, 90],
       [22, 51, 21, 28, 55, 59, 99, 46, 18, 52],
       [64, 35, 69, 46, 74, 69,  6, 98, 63, 58],
       [88, 61,  9, 67, 53, 56, 80, 26, 63, 66],
       [12, 30, 34, 43, 93, 49, 28, 32, 19, 26],
       [28, 92, 97, 70, 61, 83, 31, 65, 50, 66],
       [95,  8, 92, 98, 37, 37, 93, 87, 31, 55],
       [84,  7, 59, 78, 55, 21, 39, 92, 68, 11],
       [86, 80, 99,  4, 68, 90, 92, 86, 45, 58],
       [33, 42, 57, 73, 18, 30, 98, 18, 77, 23]])