# funciones mas comunies en numpy


In [2]:
import numpy as np

#SHAPER Y RESHAPE


In [3]:
arr = np.random.randint(1,10,(3,2))
arr

array([[4, 6],
       [3, 5],
       [8, 6]])

In [4]:
arr.shape

(3, 2)

In [5]:
arr.ndim

2

In [6]:
arr.reshape(1,6)

array([[4, 6, 3, 5, 8, 6]])

In [7]:
arr.ndim

2

#funciones estadisticas MAX Y ARGMAX

In [8]:
arr = np.random.randint(1,10,(3,2))
arr

array([[5, 2],
       [4, 4],
       [8, 5]])

In [10]:
matriz = arr.reshape(1,6)
matriz
matriz

array([[5, 2, 4, 4, 8, 5]])

In [9]:
arr.max()

8

In [12]:
matriz.max()

8

In [11]:
matriz.max(1)

array([8])

In [13]:
arr.argmax()

4

#MIN Y ARGMIN


In [18]:
arr.min()

2

In [17]:
arr.argmin()

1

In [19]:
matriz.min(0)

array([5, 2, 4, 4, 8, 5])

## sort, ordenar


In [20]:
arr

array([[5, 2],
       [4, 4],
       [8, 5]])

In [21]:
arr.sort()
arr

array([[2, 5],
       [4, 4],
       [5, 8]])

#mediana

In [22]:
np.median(arr)


4.5

## DESVIACION ESTANDAR

In [23]:
np.std(arr)

1.7950549357115013

##VARIANZA


In [24]:
np.var(arr)

3.222222222222222