In [3]:
import numpy as np

In [5]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

##FILTROS POR CONDICIONES

In [6]:
indices_condiciones=arr>5
indices_condiciones

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [11]:
arr[indices_condiciones]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [12]:
arr[arr<5]

array([1, 2, 3, 4], dtype=int8)

In [14]:
arr[(arr > 5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [15]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [16]:
arr_2 = arr[arr == 99]
arr_2

array([99, 99, 99, 99, 99], dtype=int8)

In [18]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [22]:
arr_2[arr_2 == 5] = 100
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [23]:
arr_2

array([99, 99, 99, 99, 99], dtype=int8)

#COPY

In [24]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [25]:
arr_copy = arr.copy()
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [26]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100], dtype=int8)